spring.application.name=stuff
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:stuff_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:}}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
