CREATE SEQUENCE guild_bank_sync_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE guild_bank_sync (
    id BIGINT NOT NULL,
    sync_time TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE wow_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    blizzard_id BIGINT NOT NULL,
    name VARCHAR(255),
    quality_name VARCHAR(255),
    quality_type VARCHAR(255),
    quantity BIGINT NOT NULL,
    last_sync_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_wow_item_blizzard_id UNIQUE (blizzard_id),
    CONSTRAINT fk_wow_item_last_sync
        FOREIGN KEY (last_sync_id) REFERENCES guild_bank_sync (id)
);

CREATE TABLE todo_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted BOOLEAN NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_todo_types_name UNIQUE (name)
);

CREATE TABLE todo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date DATE,
    deleted BOOLEAN NOT NULL,
    description VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    title VARCHAR(255) NOT NULL,
    todo_type_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_todo_todo_type
        FOREIGN KEY (todo_type_id) REFERENCES todo_types (id)
);
