CREATE TABLE game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    opponent VARCHAR(255) NOT NULL,
    game_time VARCHAR(255) NOT NULL,
    game_date VARCHAR(255) NOT NULL,
    court BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE SEQUENCE game_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    gender VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE game_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_game_attendance_game_player UNIQUE (game_id, player_id),
    CONSTRAINT fk_game_attendance_game
        FOREIGN KEY (game_id) REFERENCES game (id),
    CONSTRAINT fk_game_attendance_player
        FOREIGN KEY (player_id) REFERENCES player (id)
);
